name: Build Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  pull-requests: write
  issues: write

# Cancel any in-progress job or run for the same branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Get current version
        id: current-version
        run: |
          $version = node -p "require('./package.json').version"
          echo "current-version=$version" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Upload Windows installer
        uses: actions/upload-artifact@v4
        with:
          name: USB-AutoStart-Setup
          path: dist/USB AutoStart Setup ${{ steps.current-version.outputs.current-version }}.exe
          if-no-files-found: error

      - name: Upload Portable version
        uses: actions/upload-artifact@v4
        with:
          name: USB-AutoStart-Portable
          path: dist/win-unpacked/
          if-no-files-found: error

      - name: Find Comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/find-comment@v3
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '### Build Artifacts'

      - name: Create or Update Comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### Build Artifacts
            ✅ Build completed successfully!
            
            Download the artifacts:
            - [Windows Installer](https://nightly.link/${{ github.repository }}/actions/runs/${{ github.run_id }}/USB-AutoStart-Setup)
            - [Portable Version](https://nightly.link/${{ github.repository }}/actions/runs/${{ github.run_id }}/USB-AutoStart-Portable)
            
            These links will directly download the artifacts using nightly.link service.
          edit-mode: replace
