name: Release
on: workflow_dispatch
jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: git config
        run: |
          git config user.name "Release-It_Bot"
          git config user.email "Release-It_Bot@users.noreply.github.com"
      - run: npm ci
      - run: npx release-it --config release-it/version-bump.json --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run build
      - name: Create portable ZIP
        run: |
          $version = (Get-Content package.json | ConvertFrom-Json).version
          Compress-Archive -Path "dist/win-unpacked/*" -DestinationPath "dist/USB AutoStart ${version} Portable.zip"
      - run: npx release-it --config release-it/create-release.json --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
