name: Release
on: workflow_dispatch
jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: npm install
      - run: npm run build
      - name: Create portable ZIP
        run: |
          $version = (Get-Content package.json | ConvertFrom-Json).version
          Compress-Archive -Path "dist/win-unpacked/*" -DestinationPath "dist/USB AutoStart ${version} Portable.zip"
      - run: npx release-it
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
